# Generated by Django 5.0.6 on 2024-07-03 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SI_Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(blank=True, db_column='EMPRESA', max_length=50, null=True)),
            ],
            options={
                'db_table': 'SI_Empresa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SI_Linea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea', models.CharField(blank=True, db_column='LINEA', max_length=60, null=True)),
            ],
            options={
                'db_table': 'SI_Linea',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SI_Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(db_column='SECTOR', max_length=15)),
            ],
            options={
                'db_table': 'SI_Sector',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SI_TipoAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_almacen', models.CharField(blank=True, db_column='TIPO_ALMACEN', max_length=20, null=True)),
            ],
            options={
                'db_table': 'SI_TipoAlmacen',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SI_TipoProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_producto', models.CharField(db_column='TIPO_PRODUCTO', max_length=6)),
            ],
            options={
                'db_table': 'SI_TipoProductos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SI_Depositos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposito', models.CharField(db_column='DEPOSITO', max_length=15)),
                ('descripcion_deposito', models.CharField(blank=True, db_column='DESCRIPCION_DEPOSITO', max_length=60, null=True)),
                ('empr_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StockInventarioB.si_empresa')),
            ],
            options={
                'db_table': 'SI_Depositos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SI_Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(blank=True, db_column='GRUPO', max_length=60, null=True)),
                ('linea_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StockInventarioB.si_linea')),
            ],
            options={
                'db_table': 'SI_Grupo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SI_Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(db_column='PRODUCTO', max_length=30)),
                ('descripcion_producto', models.CharField(blank=True, db_column='DESCRIPCION_PRODUCTO', max_length=120, null=True)),
                ('grupo_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StockInventarioB.si_grupo')),
            ],
            options={
                'db_table': 'SI_Productos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StocksInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.DecimalField(blank=True, db_column='STOCK', decimal_places=2, max_digits=18, null=True)),
                ('lote', models.CharField(db_column='LOTE', max_length=30)),
                ('fecha_vigencia_lote', models.DateField(blank=True, db_column='FECHA_VIGENCIA_LOTE', null=True)),
                ('tipo_almacenaje', models.CharField(blank=True, db_column='TIPO_ALMACENAJE', max_length=50, null=True)),
                ('registro_sanitario', models.CharField(blank=True, db_column='REGISTRO_SANITARIO', max_length=32, null=True)),
                ('fecha_vigencia_regsan', models.DateField(blank=True, db_column='FECHA_VIGENCIA_REGSAN', null=True)),
                ('dep_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StockInventarioB.si_depositos')),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StockInventarioB.si_productos')),
                ('sector_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StockInventarioB.si_sector')),
                ('tipoAlm_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StockInventarioB.si_tipoalmacen')),
                ('tipoProd_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StockInventarioB.si_tipoproductos')),
            ],
            options={
                'db_table': 'STOCKS_INVENTARIO',
                'managed': True,
            },
        ),
    ]
