# Generated by Django 5.0.6 on 2024-08-01 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0002_si_empresa_si_linea_si_sector_si_tipoalmacen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiasRemision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_guia', models.CharField(blank=True, db_column='NUMERO_GUIA', max_length=50, null=True)),
                ('atencion', models.CharField(blank=True, db_column='ATENCION', max_length=15, null=True)),
                ('representante', models.CharField(blank=True, db_column='REPRESENTANTE', max_length=60, null=True)),
                ('motivo', models.CharField(blank=True, db_column='MOTIVO_TRASLADO', max_length=50, null=True)),
                ('cliente', models.CharField(blank=True, db_column='NOMBRE_CLIENTE', max_length=150, null=True)),
                ('entrega', models.CharField(blank=True, db_column='DIRECCION_ENTREGA', max_length=255, null=True)),
                ('fecha_guia', models.DateField(blank=True, db_column='FECHA_GUIA', null=True)),
                ('estado', models.CharField(blank=True, db_column='ESTADO', max_length=3, null=True)),
                ('id_app', models.IntegerField(blank=True, db_column='ID_APP', null=True)),
                ('obs', models.CharField(blank=True, db_column='OBSERVACION', max_length=500, null=True)),
                ('empresa', models.ForeignKey(db_column='EMPRESA_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='StockInventarioB.si_empresa')),
            ],
            options={
                'db_table': 'GUIAS_REMISION',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GR_Descripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_item', models.IntegerField(blank=True, db_column='NUMERO_ITEM', null=True)),
                ('prod_id', models.ForeignKey(db_column='PRODUCTO_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='StockInventarioB.si_productos')),
                ('sector_id', models.ForeignKey(db_column='SECTOR_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='StockInventarioB.si_sector')),
                ('guia_id', models.ForeignKey(db_column='GUIA_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='StockInventarioB.guiasremision')),
            ],
            options={
                'db_table': 'GR_DESCRIPCION',
                'managed': True,
            },
        ),
    ]
