# Generated by Django 5.0.6 on 2024-08-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0003_guiasremision_gr_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='gr_descripcion',
            name='cantidad',
            field=models.DecimalField(blank=True, db_column='CANTIDAD', decimal_places=2, max_digits=18, null=True),
        ),
    ]
