# Generated by Django 5.0.6 on 2024-08-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0005_gr_descripcion_oc_guiasremision_oc'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiasremision_oc',
            name='nro_proceso',
            field=models.CharField(blank=True, db_column='NRO_PROCESO', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='guiasremision_oc',
            name='oc_cliente',
            field=models.CharField(blank=True, db_column='OC_CLIENTE', max_length=20, null=True),
        ),
    ]
