# Generated by Django 5.0.6 on 2024-08-08 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0006_guiasremision_oc_nro_proceso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GR_Descripcion_OC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_guia', models.CharField(blank=True, db_column='NUMERO_GUIA', max_length=50, null=True)),
                ('nro_item', models.IntegerField(blank=True, db_column='NUMERO_ITEM', null=True)),
                ('cantidad', models.DecimalField(blank=True, db_column='CANTIDAD', decimal_places=2, max_digits=18, null=True)),
                ('lote', models.CharField(blank=True, db_column='LOTE', max_length=30, null=True)),
                ('venc_lote', models.DateField(blank=True, db_column='VENCIMIENTO_LOTE', null=True)),
                ('prod_id', models.ForeignKey(db_column='PRODUCTO_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='StockInventarioB.si_productos')),
                ('sector_id', models.ForeignKey(db_column='SECTOR_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='StockInventarioB.si_sector')),
            ],
            options={
                'db_table': 'GR_DESCRIPCION_OC',
                'managed': True,
            },
        ),
    ]
