# Generated by Django 5.0.6 on 2024-08-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0008_gr_descripcion_oc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gr_descripcion',
            name='guia_id',
        ),
        migrations.AddField(
            model_name='gr_descripcion',
            name='lote',
            field=models.CharField(blank=True, db_column='LOTE', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gr_descripcion',
            name='nro_guia',
            field=models.CharField(blank=True, db_column='NUMERO_GUIA', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gr_descripcion',
            name='venc_lote',
            field=models.DateField(blank=True, db_column='VENCIMIENTO_LOTE', null=True),
        ),
    ]
