# Generated by Django 5.0.6 on 2024-08-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0009_remove_gr_descripcion_guia_id_gr_descripcion_lote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GR_Busqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_guia', models.CharField(blank=True, db_column='NUMERO_GUIA', max_length=50, null=True)),
                ('id_app', models.IntegerField(blank=True, db_column='ID_APP', null=True)),
            ],
            options={
                'db_table': 'GR_BUSQUEDA',
                'managed': True,
            },
        ),
    ]
