# Generated by Django 5.0.6 on 2024-08-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0012_gr_busqueda_oc_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fact_Busqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_fact', models.CharField(blank=True, db_column='NUMERO_FACTURA', max_length=20, null=True)),
                ('id_app', models.IntegerField(blank=True, db_column='ID_APP', null=True)),
                ('fecha_emision', models.DateField(blank=True, db_column='FECHA_EMISION', null=True)),
                ('oc_cliente', models.CharField(blank=True, db_column='OC_CLIENTE', max_length=20, null=True)),
            ],
            options={
                'db_table': 'FACT_BUSQUEDA',
                'managed': True,
            },
        ),
    ]
