# Generated by Django 5.0.6 on 2024-09-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0013_fact_busqueda'),
    ]

    operations = [
        migrations.CreateModel(
            name='HojaPicking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_guia', models.CharField(blank=True, db_column='NUMERO_GUIA', max_length=50, null=True)),
                ('status_picking', models.CharField(blank=True, db_column='STATUS_PICKING', max_length=60, null=True)),
                ('atencion', models.CharField(blank=True, db_column='ATENCION', max_length=60, null=True)),
                ('firma_atencion', models.CharField(blank=True, db_column='FIRMA_ATENCION', max_length=60, null=True)),
                ('fecha_atencion', models.DateField(blank=True, db_column='FECHA_ATENCION', null=True)),
                ('almacen', models.CharField(blank=True, db_column='ALMACEN', max_length=60, null=True)),
                ('firma_almacen', models.CharField(blank=True, db_column='FIRMA_ALMACEN', max_length=60, null=True)),
                ('fecha_almacen', models.DateField(blank=True, db_column='FECHA_ALMACEN', null=True)),
                ('distribucion', models.CharField(blank=True, db_column='DISTRIBUCION', max_length=60, null=True)),
                ('firma_distribucion', models.CharField(blank=True, db_column='FIRMA_DISTRIBUCION', max_length=60, null=True)),
                ('fecha_distribucion', models.DateField(blank=True, db_column='FECHA_DISTRIBUCION', null=True)),
            ],
            options={
                'db_table': 'HOJA_PICKING',
                'managed': True,
            },
        ),
    ]
