# Generated by Django 5.0.6 on 2024-09-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0014_hojapicking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hojapicking',
            name='fecha_almacen',
            field=models.DateTimeField(blank=True, db_column='FECHA_ALMACEN', null=True),
        ),
        migrations.AlterField(
            model_name='hojapicking',
            name='fecha_atencion',
            field=models.DateTimeField(blank=True, db_column='FECHA_ATENCION', null=True),
        ),
        migrations.AlterField(
            model_name='hojapicking',
            name='fecha_distribucion',
            field=models.DateTimeField(blank=True, db_column='FECHA_DISTRIBUCION', null=True),
        ),
    ]
