# Generated by Django 5.0.6 on 2024-09-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0015_alter_hojapicking_fecha_almacen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hojapicking',
            name='oc_cliente',
            field=models.CharField(blank=True, db_column='OC_CLIENTE', max_length=20, null=True),
        ),
    ]
