# Generated by Django 5.0.6 on 2024-09-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0016_hojapicking_oc_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='hojapicking',
            name='lima_provincia',
            field=models.IntegerField(blank=True, db_column='LIMA_PROVINCIA', null=True),
        ),
    ]
