# Generated by Django 5.0.6 on 2024-09-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0017_hojapicking_lima_provincia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fact_Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_fact', models.CharField(blank=True, db_column='NUMERO_FACTURA', max_length=20, null=True)),
                ('fecha_emision', models.DateField(blank=True, db_column='FECHA_EMISION', null=True)),
                ('monto', models.IntegerField(blank=True, db_column='MONTO', null=True)),
                ('moneda', models.CharField(blank=True, db_column='MONEDA', max_length=20, null=True)),
                ('nombre_cliente', models.CharField(blank=True, db_column='NOMBRE_CLIENTE', max_length=150, null=True)),
                ('cond_pago', models.CharField(blank=True, db_column='CONDICION_PAGO', max_length=60, null=True)),
                ('vendedor', models.CharField(blank=True, db_column='VENDEDOR', max_length=60, null=True)),
                ('cancelado', models.CharField(blank=True, db_column='CANCELADO', max_length=1, null=True)),
                ('estado', models.CharField(blank=True, db_column='ESTADO', max_length=3, null=True)),
                ('cobrado', models.DecimalField(blank=True, db_column='COBRADO', decimal_places=2, max_digits=18, null=True)),
                ('saldo', models.DecimalField(blank=True, db_column='SALDO', decimal_places=2, max_digits=18, null=True)),
                ('nc_fact_canje', models.CharField(blank=True, db_column='NC_FACTURA_CANJE', max_length=35, null=True)),
                ('nc_anulacion', models.CharField(blank=True, db_column='NC_ANULACION', max_length=35, null=True)),
                ('tit_grat', models.CharField(blank=True, db_column='TITULO_GRATUITO', max_length=1, null=True)),
                ('empresa', models.CharField(blank=True, db_column='EMPRESA', max_length=150, null=True)),
                ('dir_entr', models.CharField(blank=True, db_column='DIRECCION_ENTREGA', max_length=255, null=True)),
                ('sede', models.CharField(blank=True, db_column='SEDE', max_length=60, null=True)),
                ('id_app', models.IntegerField(blank=True, db_column='ID_APP', null=True)),
                ('oc_cliente', models.CharField(blank=True, db_column='OC_CLIENTE', max_length=20, null=True)),
            ],
            options={
                'db_table': 'FACT_DETALLE',
                'managed': True,
            },
        ),
    ]
