# Generated by Django 5.0.6 on 2024-09-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0020_fact_detalle_id_fact'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact_detalle',
            name='tipo_cliente',
            field=models.CharField(blank=True, db_column='TIPO_CLIENTE', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='fact_detalle',
            name='usuario_registro',
            field=models.CharField(blank=True, db_column='USUARIO_REGISTRO', max_length=60, null=True),
        ),
    ]
