# Generated by Django 5.0.6 on 2024-09-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0021_fact_detalle_tipo_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact_detalle',
            name='id_fact',
            field=models.IntegerField(blank=True, db_column='ID_FACT', default=0),
            preserve_default=False,
        ),
    ]
