# Generated by Django 5.0.6 on 2024-09-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0022_alter_fact_detalle_id_fact'),
    ]

    operations = [
        migrations.CreateModel(
            name='HP_Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(blank=True, db_column='PRODUCTO', max_length=30, null=True)),
                ('proveedor', models.CharField(blank=True, db_column='PROVEEDOR', max_length=120, null=True)),
            ],
            options={
                'db_table': 'HP_PROVEEDOR',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='gr_descripcion',
            name='prod_id',
        ),
        migrations.RemoveField(
            model_name='gr_descripcion_oc',
            name='prod_id',
        ),
        migrations.AddField(
            model_name='gr_descripcion',
            name='prod',
            field=models.CharField(blank=True, db_column='PRODUCTO', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gr_descripcion',
            name='proveedor',
            field=models.CharField(blank=True, db_column='PROVEEDOR', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='gr_descripcion_oc',
            name='prod',
            field=models.CharField(blank=True, db_column='PRODUCTO', max_length=20, null=True),
        ),
    ]
