# Generated by Django 5.0.6 on 2024-09-26 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0023_hp_proveedor_remove_gr_descripcion_prod_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='si_productos',
            name='proveedor_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='StockInventarioB.hp_proveedor'),
            preserve_default=False,
        ),
    ]
