# Generated by Django 5.0.6 on 2024-09-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0023_hp_proveedor_remove_gr_descripcion_prod_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gr_descripcion_oc',
            name='proveedor',
            field=models.CharField(blank=True, db_column='PROVEEDOR', max_length=150, null=True),
        ),
    ]
