# Generated by Django 5.0.6 on 2024-09-27 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0024_gr_descripcion_oc_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='si_productos',
            name='proveedor_id',
            field=models.ForeignKey(db_column='PROVEEDOR_ID', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='StockInventarioB.hp_proveedor'),
            preserve_default=False,
        ),
    ]
