# Generated by Django 5.0.6 on 2024-10-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0026_stocksinventario_descr_deposito'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact_detalle',
            name='zona',
            field=models.CharField(blank=True, db_column='ZONA', max_length=60, null=True),
        ),
    ]
