# Generated by Django 5.0.6 on 2024-10-04 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0027_fact_detalle_zona'),
    ]

    operations = [
        migrations.RunSQL('ALTER TABLE FACT_DETALLE ADD RV ROWVERSION'),
    ]
