# Generated by Django 5.0.6 on 2024-10-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0029_auto_20241004_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fact_UpdateAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_fact', models.IntegerField(blank=True, db_column='ID_FACT')),
                ('nro_fact', models.CharField(blank=True, db_column='NUMERO_FACTURA', max_length=20, null=True)),
                ('estado_old', models.CharField(blank=True, db_column='ESTADO_OLD', max_length=3, null=True)),
                ('estado_new', models.CharField(blank=True, db_column='ESTADO_NEW', max_length=3, null=True)),
                ('fecha_hora', models.DateTimeField(blank=True, db_column='FECHA_HORA', null=True)),
            ],
            options={
                'db_table': 'FACT_UPDATE_AUDIT',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SI_UpdateAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_stock', models.IntegerField(blank=True, db_column='ID_SI')),
                ('lote', models.CharField(db_column='LOTE', max_length=30)),
                ('descr_deposito', models.CharField(blank=True, db_column='DESCRIPCION_DEPOSITO', max_length=60, null=True)),
                ('stock_old', models.DecimalField(blank=True, db_column='STOCK_OLD', decimal_places=2, max_digits=18, null=True)),
                ('stock_new', models.DecimalField(blank=True, db_column='STOCK_NEW', decimal_places=2, max_digits=18, null=True)),
                ('fecha_hora', models.DateTimeField(blank=True, db_column='FECHA_HORA', null=True)),
            ],
            options={
                'db_table': 'SI_UPDATE_AUDIT',
                'managed': True,
            },
        ),
    ]
