# Generated by Django 5.0.6 on 2024-10-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0030_fact_updateaudit_si_updateaudit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='si_updateaudit',
            name='id_stock',
        ),
        migrations.AddField(
            model_name='si_updateaudit',
            name='producto',
            field=models.CharField(db_column='PRODUCTO', default=0, max_length=30),
            preserve_default=False,
        ),
    ]
