# Generated by Django 5.0.6 on 2024-10-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0031_remove_si_updateaudit_id_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='si_updateaudit',
            name='sector',
            field=models.CharField(blank=True, db_column='SECTOR', max_length=15),
        ),
    ]
