# Generated by Django 5.0.6 on 2024-10-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0033_si_updateaudit_tipo_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact_updateaudit',
            name='estado_new',
            field=models.TextField(blank=True, db_column='ESTADO_NEW', null=True),
        ),
        migrations.AlterField(
            model_name='fact_updateaudit',
            name='estado_old',
            field=models.TextField(blank=True, db_column='ESTADO_OLD', null=True),
        ),
    ]
