# Generated by Django 4.2.16 on 2024-10-14 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0035_remove_si_productos_grupo_id_si_productos_grupo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='si_productos',
            name='proveedor_id',
            field=models.ForeignKey(db_column='PROVEEDOR_ID', default=5502, on_delete=django.db.models.deletion.DO_NOTHING, to='StockInventarioB.hp_proveedor'),
        ),
    ]
