# Generated by Django 4.2.16 on 2024-10-14 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0036_alter_si_productos_proveedor_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SI_UpdateAudit',
        ),
        migrations.AlterField(
            model_name='si_depositos',
            name='empr_id',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.DO_NOTHING, to='StockInventarioB.si_empresa'),
        ),
    ]
