# Generated by Django 4.2.16 on 2024-10-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0037_delete_si_updateaudit_alter_si_depositos_empr_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SI_UpdateAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(blank=True, db_column='PRODUCTO', max_length=30, null=True)),
                ('tipo_producto', models.CharField(blank=True, db_column='TIPO_PRODUCTO', max_length=6, null=True)),
                ('grupo', models.CharField(blank=True, db_column='GRUPO', max_length=60, null=True)),
                ('linea', models.CharField(blank=True, db_column='LINEA', max_length=60, null=True)),
                ('lote', models.CharField(blank=True, db_column='LOTE', max_length=30, null=True)),
                ('deposito', models.CharField(blank=True, db_column='DEPOSITO', max_length=15, null=True)),
                ('sector', models.CharField(blank=True, db_column='SECTOR', max_length=15, null=True)),
                ('estado_old', models.TextField(blank=True, db_column='ESTADO_OLD', null=True)),
                ('estado_new', models.TextField(blank=True, db_column='ESTADO_NEW', null=True)),
                ('fecha_hora', models.DateTimeField(blank=True, db_column='FECHA_HORA', null=True)),
            ],
            options={
                'db_table': 'SI_UPDATE_AUDIT',
                'managed': True,
            },
        ),
    ]
