# Generated by Django 4.2.16 on 2024-10-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0038_si_updateaudit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pend_Guias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_concat', models.CharField(blank=True, db_column='ID_CONCAT', max_length=40, null=True)),
                ('nro_guia', models.CharField(blank=True, db_column='NUMERO_GUIA', max_length=50, null=True)),
                ('repr', models.CharField(blank=True, db_column='REPRESENTANTE', max_length=60, null=True)),
                ('nombre_cliente', models.CharField(blank=True, db_column='NOMBRE_CLIENTE', max_length=150, null=True)),
                ('zona', models.CharField(blank=True, db_column='ZONA', max_length=60, null=True)),
                ('tipo_venta', models.CharField(blank=True, db_column='TIPO_VENTA', max_length=60, null=True)),
                ('empr', models.CharField(blank=True, db_column='EMPRESA', max_length=10, null=True)),
                ('f_guia', models.DateField(blank=True, db_column='FECHA_GUIA', null=True)),
                ('id_app', models.IntegerField(blank=True, db_column='ID_APP', null=True)),
            ],
            options={
                'db_table': 'PEND_GUIAS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pend_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_concat', models.CharField(blank=True, db_column='ID_CONCAT', max_length=40, null=True)),
                ('nro_guia', models.CharField(blank=True, db_column='NUMERO_GUIA', max_length=50, null=True)),
                ('item', models.IntegerField(blank=True, db_column='ITEM', null=True)),
                ('prod', models.CharField(blank=True, db_column='PRODUCTO', max_length=20, null=True)),
                ('desc_prod', models.CharField(blank=True, db_column='DESCRIPCION_PRODUCTO', max_length=120, null=True)),
                ('cant', models.IntegerField(blank=True, db_column='CANTIDAD', null=True)),
                ('lote', models.CharField(blank=True, db_column='LOTE', max_length=30, null=True)),
                ('v_lote', models.DateField(blank=True, db_column='VENCIMIENTO_LOTE', null=True)),
                ('id_app', models.IntegerField(blank=True, db_column='ID_APP', null=True)),
            ],
            options={
                'db_table': 'PEND_ITEMS',
                'managed': True,
            },
        ),
    ]
