# Generated by Django 4.2.16 on 2024-10-18 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0039_pend_guias_pend_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pend_guias',
            name='id_concat',
        ),
    ]
