# Generated by Django 4.2.16 on 2024-10-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0040_remove_pend_guias_id_concat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pend_Update_Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_concat', models.CharField(blank=True, db_column='ID_CONCAT', max_length=40, null=True)),
                ('nro_guia', models.CharField(blank=True, db_column='NUMERO_GUIA', max_length=50, null=True)),
                ('item', models.IntegerField(blank=True, db_column='ITEM', null=True)),
                ('accion', models.CharField(blank=True, db_column='ACCION', max_length=20, null=True)),
                ('cant_pend_old', models.IntegerField(blank=True, db_column='CANT_PEND_OLD', null=True)),
                ('cant_pend_new', models.IntegerField(blank=True, db_column='CANT_PEND_NEW', null=True)),
                ('f_hora', models.DateField(blank=True, db_column='FECHA_HORA', null=True)),
            ],
            options={
                'db_table': 'PEND_UPDATE_AUDIT',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='pend_items',
            name='cant',
        ),
        migrations.AddField(
            model_name='pend_items',
            name='cant_pend',
            field=models.IntegerField(blank=True, db_column='CANTIDAD_PENDIENTE', null=True),
        ),
    ]
