# Generated by Django 4.2.16 on 2024-10-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0042_alter_pend_update_audit_f_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiasremision',
            name='tipo_pedido',
            field=models.CharField(blank=True, db_column='TIPO_PEDIDO', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='guiasremision_oc',
            name='tipo_pedido',
            field=models.CharField(blank=True, db_column='TIPO_PEDIDO', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stocksinventario',
            name='codigo_qr',
            field=models.CharField(blank=True, db_column='CODIGO_QR', max_length=150, null=True),
        ),
    ]
