# Generated by Django 4.2.16 on 2024-10-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0043_guiasremision_tipo_pedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gr_descripcion',
            name='empr_id',
            field=models.IntegerField(blank=True, db_column='EMPRESA_ID', null=True),
        ),
        migrations.AddField(
            model_name='gr_descripcion_oc',
            name='empr_id',
            field=models.IntegerField(blank=True, db_column='EMPRESA_ID', null=True),
        ),
        migrations.AddField(
            model_name='hojapicking',
            name='empr_id',
            field=models.IntegerField(blank=True, db_column='EMPRESA_ID', null=True),
        ),
    ]
