# Generated by Django 4.2.16 on 2024-10-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0044_gr_descripcion_empr_id_gr_descripcion_oc_empr_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gr_descripcion',
            name='ubicacion_sector',
            field=models.CharField(blank=True, db_column='UBICACION_SECTOR', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='gr_descripcion_oc',
            name='ubicacion_sector',
            field=models.CharField(blank=True, db_column='UBICACION_SECTOR', max_length=120, null=True),
        ),
    ]
