# Generated by Django 4.2.16 on 2024-10-23 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0045_gr_descripcion_ubicacion_sector_and_more'),
    ]

    operations = [
        migrations.RunSQL('ALTER TABLE PEND_GUIAS ADD RV ROWVERSION'),
        migrations.RunSQL('ALTER TABLE PEND_ITEMS ADD RV ROWVERSION'),
    ]
