# Generated by Django 4.2.16 on 2024-10-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0046_auto_20241023_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='gr_descripcion',
            name='id_concat',
            field=models.BigIntegerField(blank=True, db_column='ID_CONCAT', null=True),
        ),
        migrations.AddField(
            model_name='gr_descripcion_oc',
            name='id_concat',
            field=models.BigIntegerField(blank=True, db_column='ID_CONCAT', null=True),
        ),
    ]
