# Generated by Django 4.2.16 on 2024-10-24 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0047_gr_descripcion_id_concat_gr_descripcion_oc_id_concat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hojapicking',
            name='ubicacion_sector',
        ),
    ]
