# Generated by Django 4.2.16 on 2024-10-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0048_remove_hojapicking_ubicacion_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='pend_guias',
            name='cant_pend',
            field=models.IntegerField(blank=True, db_column='CANT_PEND_TOTAL', null=True),
        ),
    ]
