# Generated by Django 4.2.16 on 2024-10-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0049_pend_guias_cant_pend'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksinventario',
            name='producto',
            field=models.CharField(blank=True, db_column='PRODUCTO', max_length=30, null=True),
        ),
    ]
