# Generated by Django 4.2.16 on 2024-11-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0050_stocksinventario_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='gr_descripcion',
            name='codigo_qr',
            field=models.CharField(blank=True, db_column='CODIGO_QR', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='gr_descripcion',
            name='kits_items',
            field=models.CharField(blank=True, db_column='KITS_ITEM', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='gr_descripcion_oc',
            name='codigo_qr',
            field=models.CharField(blank=True, db_column='CODIGO_QR', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='gr_descripcion_oc',
            name='kits_items',
            field=models.CharField(blank=True, db_column='KITS_ITEM', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='guiasremision',
            name='kits_guia',
            field=models.CharField(blank=True, db_column='KITS_GUIA', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='guiasremision',
            name='paciente',
            field=models.CharField(blank=True, db_column='PACIENTE', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='guiasremision',
            name='ruc_cliente',
            field=models.CharField(blank=True, db_column='RUC_CLIENTE', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='guiasremision_oc',
            name='kits_guia',
            field=models.CharField(blank=True, db_column='KITS_GUIA', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='guiasremision_oc',
            name='paciente',
            field=models.CharField(blank=True, db_column='PACIENTE', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='guiasremision_oc',
            name='ruc_cliente',
            field=models.CharField(blank=True, db_column='RUC_CLIENTE', max_length=20, null=True),
        ),
    ]
