# Generated by Django 4.2.16 on 2024-11-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0051_gr_descripcion_codigo_qr_gr_descripcion_kits_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hojapicking',
            name='empr_id',
            field=models.BigIntegerField(blank=True, db_column='EMPRESA_ID', null=True),
        ),
    ]
