# Generated by Django 4.2.16 on 2024-11-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0053_alter_hojapicking_empr_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pend_Guias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_guia', models.CharField(blank=True, db_column='NUMERO_GUIA', max_length=50, null=True)),
                ('repr', models.CharField(blank=True, db_column='REPRESENTANTE', max_length=60, null=True)),
                ('nombre_cliente', models.CharField(blank=True, db_column='NOMBRE_CLIENTE', max_length=150, null=True)),
                ('zona', models.CharField(blank=True, db_column='ZONA', max_length=60, null=True)),
                ('tipo_venta', models.CharField(blank=True, db_column='TIPO_VENTA', max_length=60, null=True)),
                ('empr', models.CharField(blank=True, db_column='EMPRESA', max_length=10, null=True)),
                ('f_guia', models.DateField(blank=True, db_column='FECHA_GUIA', null=True)),
                ('id_app', models.IntegerField(blank=True, db_column='ID_APP', null=True)),
                ('cant_pend', models.IntegerField(blank=True, db_column='CANT_PEND_TOTAL', null=True)),
            ],
            options={
                'db_table': 'PEND_GUIAS',
                'managed': True,
            },
        ),
    ]
