# Generated by Django 4.2.16 on 2024-11-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0056_gr_busqueda_fecha_cirugia'),
    ]

    operations = [
        migrations.AddField(
            model_name='gr_busqueda',
            name='zona',
            field=models.CharField(blank=True, db_column='ZONA', max_length=60, null=True),
        ),
    ]
