# Generated by Django 4.2.16 on 2024-11-13 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0059_hojapicking_gr_id_hojapicking_gr_oc_id'),
    ]

    operations = [
        migrations.RunSQL('ALTER TABLE PEND_GUIAS ADD RV ROWVERSION'),
    ]
