# Generated by Django 4.2.16 on 2024-11-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0061_hojapicking_cliente_hojapicking_motivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiasremision',
            name='fecha_cirugia',
            field=models.DateField(blank=True, db_column='FECHA_CIRUGIA', null=True),
        ),
        migrations.AddField(
            model_name='guiasremision_oc',
            name='fecha_cirugia',
            field=models.DateField(blank=True, db_column='FECHA_CIRUGIA', null=True),
        ),
    ]
