# Generated by Django 4.2.16 on 2024-11-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0062_guiasremision_fecha_cirugia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hojapicking',
            name='nro_proceso',
            field=models.CharField(blank=True, db_column='NRO_PROCESO', max_length=20, null=True),
        ),
    ]
