# Generated by Django 4.2.16 on 2024-11-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0063_hojapicking_nro_proceso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gr_descripcion',
            name='sector_id',
        ),
        migrations.RemoveField(
            model_name='gr_descripcion_oc',
            name='sector_id',
        ),
        migrations.AddField(
            model_name='gr_descripcion',
            name='sector',
            field=models.CharField(blank=True, db_column='SECTOR', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='gr_descripcion_oc',
            name='sector',
            field=models.CharField(blank=True, db_column='SECTOR', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='hojapicking',
            name='sector',
            field=models.CharField(blank=True, db_column='SECTOR', max_length=15, null=True),
        ),
    ]
