# Generated by Django 4.2.16 on 2024-12-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0064_remove_gr_descripcion_sector_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact_detalle',
            name='afecto_detr',
            field=models.CharField(blank=True, db_column='AFECTO_DETRACCION', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='fact_detalle',
            name='afecto_ret',
            field=models.CharField(blank=True, db_column='AFECTO_RETENCION', max_length=1, null=True),
        ),
    ]
