# Generated by Django 4.2.16 on 2024-12-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0065_fact_detalle_afecto_detr_fact_detalle_afecto_ret'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact_detalle',
            name='monto_soles',
            field=models.DecimalField(blank=True, db_column='MONTO_SOLES', decimal_places=2, max_digits=18, null=True),
        ),
    ]
