# Generated by Django 4.2.16 on 2024-12-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0066_fact_detalle_monto_soles'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksinventario',
            name='descr_prod',
            field=models.CharField(blank=True, db_column='DESCRIPCION_PRODUCTO', max_length=120, null=True),
        ),
    ]
