# Generated by Django 4.2.16 on 2024-12-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0068_guiasremision_deposito_guiasremision_oc_deposito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gr_descripcion',
            name='kits_items',
            field=models.CharField(blank=True, db_column='KITS_ITEM', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='gr_descripcion_oc',
            name='kits_items',
            field=models.CharField(blank=True, db_column='KITS_ITEM', max_length=120, null=True),
        ),
    ]
