# Generated by Django 4.2.16 on 2025-01-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0069_alter_gr_descripcion_kits_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hojapicking',
            name='motivo',
        ),
        migrations.AddField(
            model_name='hojapicking',
            name='tipo_venta',
            field=models.CharField(blank=True, db_column='TIPO_VENTA', max_length=60, null=True),
        ),
    ]
