# Generated by Django 4.2.16 on 2025-01-14 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0070_remove_hojapicking_motivo_hojapicking_tipo_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='HP_UpdateAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_hp', models.IntegerField(blank=True, db_column='ID_HP')),
                ('nro_guia', models.CharField(blank=True, db_column='NUMERO_GUIA', max_length=20, null=True)),
                ('estado_old', models.TextField(blank=True, db_column='ESTADO_OLD', null=True)),
                ('estado_new', models.TextField(blank=True, db_column='ESTADO_NEW', null=True)),
                ('fecha_hora', models.DateTimeField(blank=True, db_column='FECHA_HORA', null=True)),
                ('picking_time', models.TimeField(blank=True, db_column='PICKING_TIME', null=True)),
                ('empr_id', models.ForeignKey(blank=True, db_column='EMPRESA_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='StockInventarioB.si_empresa')),
            ],
            options={
                'db_table': 'HP_UPDATE_AUDIT',
                'managed': True,
            },
        ),
    ]
