# Generated by Django 4.2.16 on 2025-01-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0071_hp_updateaudit'),
    ]

    operations = [
        migrations.CreateModel(
            name='GR_UpdateAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_guia', models.CharField(blank=True, db_column='NUMERO_GUIA', max_length=50, null=True)),
                ('empresa', models.IntegerField(blank=True, db_column='EMPRESA_ID', null=True)),
                ('nro_item', models.IntegerField(blank=True, db_column='NUMERO_ITEM', null=True)),
                ('estado_old', models.TextField(blank=True, db_column='ESTADO_OLD', null=True)),
                ('estado_new', models.TextField(blank=True, db_column='ESTADO_NEW', null=True)),
                ('fecha_hora', models.DateTimeField(blank=True, db_column='FECHA_HORA', null=True)),
            ],
            options={
                'db_table': 'GR_UPDATE_AUDIT',
                'managed': True,
            },
        ),
    ]
