# Generated by Django 4.2.16 on 2025-01-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0072_gr_updateaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='gr_updateaudit',
            name='id_concat',
            field=models.BigIntegerField(blank=True, db_column='ID_CONCAT', null=True),
        ),
    ]
