# Generated by Django 4.2.16 on 2025-01-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0073_gr_updateaudit_id_concat'),
    ]

    operations = [
        migrations.AddField(
            model_name='gr_descripcion',
            name='tipo_producto',
            field=models.CharField(blank=True, db_column='TIPO_PRODUCTO', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='gr_descripcion_oc',
            name='tipo_producto',
            field=models.CharField(blank=True, db_column='TIPO_PRODUCTO', max_length=6, null=True),
        ),
    ]
