# Generated by Django 4.2.16 on 2025-02-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0074_gr_descripcion_tipo_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gr_busqueda',
            name='fecha_guia',
            field=models.DateTimeField(blank=True, db_column='FECHA_GUIA', null=True),
        ),
        migrations.AlterField(
            model_name='guiasremision',
            name='fecha_guia',
            field=models.DateTimeField(blank=True, db_column='FECHA_GUIA', null=True),
        ),
        migrations.AlterField(
            model_name='guiasremision_oc',
            name='fecha_guia',
            field=models.DateTimeField(blank=True, db_column='FECHA_GUIA', null=True),
        ),
        migrations.AlterField(
            model_name='pend_guias',
            name='f_guia',
            field=models.DateTimeField(blank=True, db_column='FECHA_GUIA', null=True),
        ),
    ]
