# Generated by Django 4.2.16 on 2025-03-11 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0075_alter_gr_busqueda_fecha_guia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gr_busqueda',
            name='empresa',
            field=models.ForeignKey(blank=True, db_column='EMPRESA_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='StockInventarioB.si_empresa'),
        ),
    ]
