# Generated by Django 4.2.16 on 2025-03-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0076_gr_busqueda_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='gr_descripcion',
            name='id_app',
            field=models.IntegerField(blank=True, db_column='ID_APP', null=True),
        ),
        migrations.AddField(
            model_name='gr_descripcion_oc',
            name='id_app',
            field=models.IntegerField(blank=True, db_column='ID_APP', null=True),
        ),
    ]
