# Generated by Django 4.2.16 on 2025-03-24 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0077_gr_descripcion_id_app_gr_descripcion_oc_id_app'),
    ]

    operations = [
        migrations.RunSQL('ALTER TABLE MEDICO_PWRAPP ADD RV ROWVERSION'),
    ]
