# Generated by Django 4.2.16 on 2025-03-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0078_auto_20250324_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_coleg', models.CharField(blank=True, db_column='NRO_COLEGIATURA', max_length=20, null=True)),
                ('nombre_med', models.CharField(blank=True, db_column='NOMBRE_MEDICO', max_length=60, null=True)),
            ],
            options={
                'db_table': 'MEDICOS',
                'managed': True,
            },
        ),
    ]
