# Generated by Django 4.2.16 on 2025-03-24 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockInventarioB', '0079_medicos'),
    ]

    operations = [
        migrations.RunSQL('ALTER TABLE MEDICOS ADD RV ROWVERSION'),
    ]